[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pda_anchor = "89hhR6ZEEQ388w6FBPFKz25oDRXXWSA8hrCK6BFR3iW1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dayanarp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
