[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
manejador_eventos = "4if2krQowWzTGQ1BQKdVXkBDNa173jKKyquCHVeys52z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dayanarp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
